format = """
$time\
[  ](bold #e3c78a)\
$os\
[  ](bold #80a0ff)\
$directory\
[  ](bold #ff5454)\
$git_branch\
$git_status\
$character\
"""

right_format = """
$time\
"""

[os]
disabled = false
style = "bold fg:#80a0ff"
format = '[$symbol$name]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
openSUSE = " "
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
EndeavourOS= " "

[directory]
style = "bold fg:#ff5454"
format = '[  $path]($style)'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = "󰋜 "

[git_branch]
symbol = ""
style = "blink bold fg:#8cc85f"
format = '[$symbol $branch ]($style)'

[git_status]
style = "blink bold fg:#8cc85f"
format = '[$all_status$ahead_behind  ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bold fg:#e3c78a"
format = '[ 󱑂 $time]($style)'

[character]
disabled = false
success_symbol = '[󱦰 ](bold fg:#8cc85f)'
error_symbol = '[󱦰 ](bold fg:#ff5454)'
